#version: "3.9"
#
#services:
#  react-app: 
#    build: ./client
#    stdin_open: true
#    ports:
#      - "3000:3000"  
#  api-server:
#    depends_on:
#      - mysqldb
#    build: ./server
#    image: pet_food_server
#    stdin_open: true   
#    ports: 
#      - "4000:4000"
#  mysqldb:
#    image: mysql:5.7
#    restart: unless-stopped
#    env_file: ./.env
#    environment: 
#      - MYSQL_ROOT_PASSWORD="$PASSWORD"
#      - MYSQL_DATABASE:="$DATABASE"
#    ports:
#    # <Port exposed> : < MySQL Port running inside container> 
#      - "3307:3306"
#    expose:
#    # Opens port 3306 on the container
#      - "3306"
#    volumes: 
#      - db:/var/lib/mysql
#      - /app/node_modules
#
#volumes:
#  db:

#version: '3.9'
#services:
#  mysqldb:
#    image: mysql:5.7
#    restart: unless-stopped
#    env_file: ./.env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$PASSWORD
#      - MYSQL_DATABASE=$DATABASE
#    ports:
#      #local port:docker port
#      - "3307:3306"
#    volumes:
#      - db:/var/lib/mysql
#      #- /app/node_modules
#    networks:
#      - backend 
#  api-server:
#    depends_on:
#      - mysqldb
#    build: ./server
#    restart: unless-stopped
#    env_file: ./.env
#    ports:
#      #Node ports
#      - "4000:4000"
#    environment:
#      - DB_HOST=mysqldb
#      - DB_USER=$MYSQLDB_USER
#      - DB_PASSWORD=$PASSWORD
#      - DB_NAME=$MYSQLDB_DATABASE
#      - DB_PORT=$MYSQLDB_DOCKER_PORT  
#    networks:
#      - backend
#      - frontend
#  react-app:
#    depends_on:
#      - api-server
#    build: ./client
#    stdin_open: true
#    ports:
#      - "3000:3000"
#    networks:
#      - frontend  
#volumes: 
#  db:
#networks:
#  backend:
#  frontend:

version: '3.9'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$PASSWORD
      - MYSQL_DATABASE=$DATABASE
    ports:
      #local port:docker port
      #connect through port 3307
      - '3307:3306' 
    volumes:
      - db:/var/lib/mysql
      # - /home/user/db/mysql/data:/var/lib/mysql
      # - /home/user/db/mysql/init:/docker-entrypoint-initdb.d/:ro
  ###################################
  api-server:
    depends_on:
      - mysqldb
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '4000:4000'
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT 
    stdin_open: true
    tty: true
  ####################################
  react-app:
    depends_on:
    - api-server
    build: ./client
    stdin_open: true
    ports:
      - '3000:3000'

volumes: 
  db: