version: '3.9'

services:
  mysqldb:
    build: ./database
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$PASSWORD
      - MYSQL_DATABASE=$DATABASE
    ports:
      #local port:docker port
      #connect through port 3307
      - '3307:3306' 
    #command: --init-file /data/application/init.sql
    volumes:
      - db:/var/lib/mysql

  api-server:
    depends_on:
      - mysqldb
    build: ./server
    restart: always
    env_file: ./.env
    ports:
      - '4000:4000' 
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT 
    stdin_open: true
    tty: true
  
  react-app:
    depends_on:
    - api-server
    build: ./client
    stdin_open: true
    ports:
      - '3000:3000'

volumes: 
  db: